### PR TITLE
Use "some" to short circuit each computed update

### PR DESCRIPTION
**Pull request by 2hu12**

### CODE REVIEW

**Comment by chenzhutian** [comment]
your updated has been integrated into my ts version
https://github.com/wechat-miniprogram/computed/pull/48

**Comment by LastLeaf** [comment]
The code should be able to run on iOS>=10. I am not sure the method can work properly on old iOS. Can you make sure it works?

**Comment by 2hu12** [comment]
> The code should be able to run on iOS>=10. I am not sure the method can work properly on old iOS. Can you make sure it works?

`Array.prototype.some` should work at least on iOS 10 according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some#Browser_compatibility

**Comment by LastLeaf** [comment]
> > The code should be able to run on iOS>=10. I am not sure the method can work properly on old iOS. Can you make sure it works?
> 
> @LastLeaf `Array.prototype.some` should work at least on iOS 10 according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some#Browser_compatibility

We discovered that many native object methods in old iOS have strange behaviors, so it is better to do real tests on these systems.

However, I think there is little chance to be broken (and it is hard to find such devices). We can just rollback this change if there is related feedback in future.

This change will be delivered to npm with #48 refactor.

Thanks for your contribution!

**Pull request merged**
